/**
 * Curated emoji suggestions for poetic / lyric keyword lookup.
 * Kept separate from WordResult so syllable and meter code never see emoji.
 */
const EMOJI_MAP: Record<string, string[]> = {
  night: ["🌙", "🌌", "🌑", "🌃"],
  moon: ["🌕", "🌙", "🌝", "🌜"],
  sun: ["☀️", "🌅", "🌄", "🌞"],
  star: ["⭐", "✨", "🌟", "💫"],
  love: ["❤️", "💕", "💘", "💗"],
  heart: ["❤️", "💔", "💖", "🫀"],
  fire: ["🔥", "🌋", "💥"],
  water: ["💧", "🌊", "💦"],
  sea: ["🌊", "🏖️", "🧜"],
  ocean: ["🌊", "🐋", "⚓"],
  rain: ["🌧️", "☔", "💧"],
  storm: ["⛈️", "🌩️", "🌪️"],
  wind: ["💨", "🍃", "🌬️"],
  cloud: ["☁️", "⛅", "🌥️"],
  snow: ["❄️", "🌨️", "⛄"],
  flower: ["🌸", "🌺", "🌹", "🌻"],
  rose: ["🌹", "🥀", "💐"],
  tree: ["🌳", "🌲", "🌴"],
  leaf: ["🍃", "🍂", "🍁"],
  bird: ["🐦", "🕊️", "🦅"],
  raven: ["🐦‍⬛", "🖤"],
  wolf: ["🐺", "🌕"],
  dream: ["💭", "😴", "✨"],
  sleep: ["😴", "💤", "🛏️"],
  death: ["💀", "☠️", "🪦"],
  ghost: ["👻", "🌑"],
  dark: ["🌑", "🖤", "🕶️"],
  light: ["💡", "✨", "🕯️"],
  candle: ["🕯️", "🔥"],
  time: ["⏳", "⌛", "🕰️"],
  clock: ["🕐", "⏰", "🕰️"],
  music: ["🎵", "🎶", "🎼"],
  song: ["🎤", "🎵", "🎶"],
  dance: ["💃", "🕺", "🩰"],
  tear: ["😢", "😭", "💧"],
  cry: ["😢", "😭", "😿"],
  smile: ["😊", "😄", "🙂"],
  laugh: ["😂", "🤣", "😆"],
  anger: ["😠", "💢", "🔥"],
  fear: ["😨", "😰", "👻"],
  hope: ["🌟", "🌈", "🙏"],
  peace: ["☮️", "🕊️", "🙏"],
  war: ["⚔️", "🪖", "💥"],
  crown: ["👑", "💎"],
  gold: ["🥇", "✨", "💰"],
  silver: ["🥈", "⚪"],
  blood: ["🩸", "❤️"],
  shadow: ["🌑", "👤", "🖤"],
  mirror: ["🪞", "✨"],
  door: ["🚪", "🔑"],
  key: ["🔑", "🗝️"],
  book: ["📖", "📚", "✍️"],
  pen: ["✒️", "🖊️", "✍️"],
  letter: ["✉️", "💌", "📝"],
  home: ["🏠", "🏡", "❤️"],
  journey: ["🛤️", "🗺️", "🚶"],
  road: ["🛣️", "🛤️", "🚗"],
  mountain: ["⛰️", "🏔️", "🗻"],
  river: ["🏞️", "🌊", "🐟"],
  forest: ["🌲", "🌳", "🦌"],
  garden: ["🌷", "🦋", "🐝"],
  butterfly: ["🦋", "🌸"],
  bee: ["🐝", "🍯"],
  wine: ["🍷", "🍇"],
  coffee: ["☕", "🤎"],
  magic: ["🪄", "✨", "🔮"],
  crystal: ["💎", "🔮", "✨"],
  angel: ["👼", "😇", "🪽"],
  devil: ["😈", "🔥"],
  heaven: ["☁️", "😇", "✨"],
  hell: ["🔥", "😈", "🌋"],
  forever: ["♾️", "💫"],
  alone: ["😔", "🌑", "👤"],
  friend: ["🤝", "💛", "🫂"],
  mother: ["👩", "💕", "🌷"],
  father: ["👨", "💙"],
  child: ["👶", "🧒", "🧸"],
  baby: ["👶", "🍼", "💙"],
  wedding: ["💒", "💍", "👰"],
  kiss: ["💋", "😘", "💞"],
  broken: ["💔", "🧩"],
  lonely: ["😔", "🌙", "🌧️"],
  happy: ["😊", "🎉", "🌈"],
  sad: ["😢", "🌧️", "💙"],
  wild: ["🦁", "🌿", "⚡"],
  free: ["🕊️", "🌬️", "🔓"],
  cage: ["🔒", "🐦"],
  fly: ["🕊️", "✈️", "🦋"],
  fall: ["🍂", "📉", "💔"],
  rise: ["🌅", "📈", "🦅"],
  dawn: ["🌅", "🌄", "☀️"],
  dusk: ["🌇", "🌆", "🌙"],
  winter: ["❄️", "🧣", "⛄"],
  spring: ["🌱", "🌸", "🌷"],
  summer: ["☀️", "🏖️", "🍉"],
  autumn: ["🍂", "🍁", "🎃"],
  city: ["🏙️", "🌃", "🚕"],
  street: ["🛣️", "🚦", "🏙️"],
  neon: ["💜", "💙", "✨"],
  ghostly: ["👻", "🌫️"],
  mist: ["🌫️", "🌁"],
  fog: ["🌫️", "🌁"],
  thunder: ["⚡", "🌩️"],
  lightning: ["⚡", "🌩️"],
  ash: ["🖤", "🌫️"],
  ember: ["🔥", "✨"],
  flame: ["🔥", "🕯️"],
  ice: ["🧊", "❄️"],
  stone: ["🪨", "🗿"],
  iron: ["⚙️", "🛡️"],
  sword: ["⚔️", "🗡️"],
  shield: ["🛡️", "⚔️"],
  arrow: ["🏹", "➡️"],
  chain: ["⛓️", "🔗"],
  wing: ["🪽", "🕊️"],
  eye: ["👁️", "👀"],
  soul: ["👻", "✨", "💜"],
  spirit: ["👻", "✨", "🌬️"],
  memory: ["🧠", "💭", "📷"],
  silence: ["🤫", "🔇", "😶"],
  whisper: ["🤫", "💨"],
  scream: ["😱", "📢"],
  echo: ["📢", "🔁"],
  void: ["⬛", "🌌"],
  infinity: ["♾️", "🌌"],
  universe: ["🌌", "🪐", "🌍"],
  earth: ["🌍", "🌎", "🌏"],
  sky: ["🌤️", "🌌", "☁️"],
  heavenward: ["⬆️", "☁️"],
  grave: ["🪦", "⚰️", "🌹"],
  crypt: ["🪦", "🕯️"],
  thorn: ["🌹", "🥀"],
  veil: ["👰", "🌫️"],
  gothic: ["🖤", "🦇", "🕯️"],
  bat: ["🦇", "🌙"],
  spider: ["🕷️", "🕸️"],
  web: ["🕸️", "🕷️"],
  poison: ["☠️", "🧪"],
  potion: ["🧪", "⚗️"],
  witch: ["🧙‍♀️", "🧹", "🪄"],
  wizard: ["🧙‍♂️", "🪄", "✨"],
  fairy: ["🧚", "✨", "🌸"],
  dragon: ["🐉", "🔥"],
  unicorn: ["🦄", "✨"],
  phoenix: ["🔥", "🦅", "✨"],
  mermaid: ["🧜‍♀️", "🌊"],
  pirate: ["🏴‍☠️", "⚓", "🦜"],
  ship: ["🚢", "⛵", "⚓"],
  boat: ["⛵", "🛶"],
  island: ["🏝️", "🌴", "🏖️"],
  desert: ["🏜️", "🌵", "☀️"],
  jungle: ["🌴", "🦜", "🐆"],
  volcano: ["🌋", "🔥"],
  earthquake: ["🌍", "💥"],
  tsunami: ["🌊", "⚠️"],
  rainbow: ["🌈", "☀️", "🌧️"],
  aurora: ["🌌", "✨", "💚"],
  comet: ["☄️", "💫"],
  planet: ["🪐", "🌍"],
  galaxy: ["🌌", "✨"],
  blackhole: ["🕳️", "🌌"],
  robot: ["🤖", "⚙️"],
  cyber: ["💻", "🤖", "⚡"],
  glitch: ["📺", "⚡", "👾"],
  code: ["💻", "⌨️", "🔢"],
  money: ["💰", "💵", "🤑"],
  power: ["⚡", "💪", "👑"],
  fight: ["🥊", "⚔️", "💥"],
  victory: ["🏆", "🥇", "✌️"],
  defeat: ["🏳️", "😔"],
  party: ["🎉", "🥳", "🎊"],
  champagne: ["🥂", "🍾"],
  cocktail: ["🍸", "🍹"],
  beer: ["🍺", "🍻"],
  cake: ["🎂", "🍰"],
  chocolate: ["🍫", "🤎"],
  apple: ["🍎", "🍏"],
  cherry: ["🍒", "❤️"],
  grape: ["🍇", "🍷"],
  lemon: ["🍋", "💛"],
  orange: ["🍊", "🧡"],
  peach: ["🍑", "🧡"],
  berry: ["🫐", "🍓"],
  honey: ["🍯", "🐝"],
  milk: ["🥛", "🐄"],
  bread: ["🍞", "🥖"],
  salt: ["🧂", "🌊"],
  sugar: ["🍬", "🍭"],
  spice: ["🌶️", "🔥"],
  bitter: ["😖", "🍋"],
  sweet: ["🍬", "😊"],
  cold: ["🥶", "❄️"],
  hot: ["🥵", "🔥"],
  soft: ["☁️", "🧸"],
  hard: ["🪨", "💪"],
  sharp: ["🗡️", "🔪"],
  smooth: ["🌊", "✨"],
  rough: ["🪨", "🌊"],
  quiet: ["🤫", "🔇"],
  loud: ["📢", "🔊"],
  fast: ["⚡", "🏃"],
  slow: ["🐢", "🐌"],
  young: ["🌱", "👶"],
  old: ["👴", "📜"],
  new: ["✨", "🆕"],
  ancient: ["🏺", "📜", "🏛️"],
  modern: ["🏙️", "📱", "💻"],
  slang: ["🧢", "💬", "🔥"],
  vibe: ["✨", "😎", "🎵"],
  cool: ["😎", "❄️", "🆒"],
  lit: ["🔥", "✨"],
  ghosted: ["👻", "📵"],
  crush: ["😍", "💘"],
  date: ["📅", "💑", "🌹"],
  text: ["💬", "📱"],
  call: ["📞", "☎️"],
  miss: ["😢", "💭"],
  wait: ["⏳", "⌛"],
  come: ["👋", "➡️"],
  go: ["➡️", "🏃"],
  stay: ["🏡", "✋"],
  leave: ["🚪", "👋"],
  return: ["↩️", "🏠"],
  begin: ["▶️", "🌱"],
  end: ["⏹️", "🏁"],
  forevermore: ["♾️", "💍"],
};

export function getEmojisForWord(query: string): string[] {
  const cleaned = query.trim().toLowerCase();
  if (!cleaned) return [];

  const exact = EMOJI_MAP[cleaned];
  if (exact) return exact;

  const matches: string[] = [];
  const seen = new Set<string>();

  for (const [key, emojis] of Object.entries(EMOJI_MAP)) {
    if (cleaned.includes(key) || key.includes(cleaned)) {
      for (const emoji of emojis) {
        if (!seen.has(emoji)) {
          seen.add(emoji);
          matches.push(emoji);
        }
      }
    }
  }

  return matches.slice(0, 8);
}
